version: 0.2
env:
   parameter-store:
        PARAMETER_COGNITO_AUTHORITY: "/ImageRecognition/Cognito/Authority"
        PARAMETER_COGNITO_METADATAURL: "/ImageRecognition/Cognito/MetadataUrl"
        PARAMETER_COGNITO_CLIENT_ID: "/ImageRecognition/Cognito/ClientId"
        PARAMETER_COGNITO_REDIRECT_URI: "/ImageRecognition/Cognito/RedirectUri"
        PARAMETER_COGNITO_POST_LOGOUT_REDIRECT_URI: "/ImageRecognition/Cognito/PostLogoutRedirectUri"
        PARAMETER_APPOPTIONS_API: "/ImageRecognition/AppOptions/ImageRecognitionApiGatewayUrl"
        PARAMETER_APPOPTIONS_WEB_SOCKET_API: "/ImageRecognition/AppOptions/ImageRecognitionWebSocketAPI"
        PARAMETER_APPOPTIONS_PHOTO_STORAGE_BUCKET: "/ImageRecognition/AppOptions/PhotoStorageBucket"

phases:
  install:
    commands:
      - yum update -y && yum install -y clang krb5-devel openssl-devel libicu llvm zip jq
      - yum install -y tar gzip
      - curl -LO https://dot.net/v1/dotnet-install.sh
      - chmod +x dotnet-install.sh
      - ./dotnet-install.sh -Channel 7.0 -Version latest
      - export PATH=/root/.dotnet:$PATH
  build:
    commands:
      - cd ./Application/UI/Blazor/ImageRecognition.BlazorWebAssembly
      - jq --arg newkey "$PARAMETER_COGNITO_AUTHORITY" '(.Cognito.Authority |= $newkey') wwwroot/appsettings.json > tmp && mv tmp wwwroot/appsettings.json
      - jq --arg newkey "$PARAMETER_COGNITO_METADATAURL" '(.Cognito.MetadataUrl |= $newkey') wwwroot/appsettings.json > tmp && mv tmp wwwroot/appsettings.json
      - jq --arg newkey "$PARAMETER_COGNITO_CLIENT_ID" '(.Cognito.ClientId |= $newkey') wwwroot/appsettings.json > tmp && mv tmp wwwroot/appsettings.json
      - jq --arg newkey "$PARAMETER_COGNITO_REDIRECT_URI" '(.Cognito.RedirectUri |= $newkey') wwwroot/appsettings.json > tmp && mv tmp wwwroot/appsettings.json
      - jq --arg newkey "$PARAMETER_COGNITO_POST_LOGOUT_REDIRECT_URI" '(.Cognito.PostLogoutRedirectUri |= $newkey') wwwroot/appsettings.json > tmp && mv tmp wwwroot/appsettings.json
      - jq --arg newkey "$PARAMETER_APPOPTIONS_API" '(.AppOptions.ImageRecognitionApiGatewayUrl |= $newkey') wwwroot/appsettings.json > tmp && mv tmp wwwroot/appsettings.json
      - jq --arg newkey "$PARAMETER_APPOPTIONS_WEB_SOCKET_API" '(.AppOptions.ImageRecognitionWebSocketAPI |= $newkey') wwwroot/appsettings.json > tmp && mv tmp wwwroot/appsettings.json
      - jq --arg newkey "$PARAMETER_APPOPTIONS_PHOTO_STORAGE_BUCKET" '(.AppOptions.PhotoStorageBucket |= $newkey') wwwroot/appsettings.json > tmp && mv tmp wwwroot/appsettings.json

      - dotnet publish "ImageRecognition.BlazorWebAssembly.csproj" -r linux-x64 -c Release --output publish
artifacts:
  files:
    - '**/*'
  base-directory: ./Application/UI/Blazor/ImageRecognition.BlazorWebAssembly/publish/wwwroot/