version: 0.2

env:
    parameter-store:
        DOCKER_TAG: "/ImageRecognition/FrontendTag"
        DOCKER_REPO: "/ImageRecognition/FrontendRepository"
phases:
  install:
    commands:
      - curl https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
      - ./dotnet-install.sh -c 6.0
      - dotnet tool install -g Amazon.ECS.Tools
  build:
    commands:
      - cd ./Application/UI/Blazor/ImageRecognition
      - /root/.dotnet/tools/dotnet-ecs push-image --config-file codebuild-defaults.json --tag $DOCKER_TAG
  post_build:
    commands:
      - printf '[{"name":"ImageRecognitionBlazerFrontend","imageUri":"%s"}]' $DOCKER_REPO > imagedefinitions.json
artifacts:
  files:
    - ./Application/UI/Blazor/ImageRecognition/imagedefinitions.json
  discard-paths: yes